# Generated by Django 5.2.3 on 2025-06-23 09:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='bangladesh', max_length=100)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('scheduled_hours', models.PositiveIntegerField(default=1)),
                ('end_time', models.DateTimeField(default=datetime.datetime(2025, 6, 23, 10, 36, 7, 7878, tzinfo=datetime.timezone.utc))),
                ('max_contents', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scraping_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api.scrapingtask')),
            ],
        ),
    ]
