# Generated by Django 5.2.3 on 2025-06-24 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingtask',
            name='category',
            field=models.CharField(default='bangladesh', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 9, 1, 48, 298076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
