# Generated by Django 5.2.3 on 2025-06-24 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_scrapingtask_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingtask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 9, 53, 27, 899489, tzinfo=datetime.timezone.utc)),
        ),
    ]
