# Generated by Django 5.2.3 on 2025-06-24 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_scrapingtask_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingtask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 9, 56, 30, 840459, tzinfo=datetime.timezone.utc)),
        ),
    ]
