# Generated by Django 5.2.3 on 2025-06-24 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_scrapingtask_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapingtask',
            old_name='is_active',
            new_name='is_activea',
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 10, 2, 34, 756290, tzinfo=datetime.timezone.utc)),
        ),
    ]
