# Generated by Django 5.2.3 on 2025-06-24 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_is_active_scrapingtask_is_activea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapingtask',
            old_name='is_activea',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 10, 3, 3, 527066, tzinfo=datetime.timezone.utc)),
        ),
    ]
