# Generated by Django 5.2.3 on 2025-06-24 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_is_activea_scrapingtask_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingtask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 10, 5, 14, 609488, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
