# Generated by Django 5.2.3 on 2025-06-24 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_scrapingtask_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingtask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 10, 6, 7, 407422, tzinfo=datetime.timezone.utc)),
        ),
    ]
