# Generated by Django 5.2.3 on 2025-06-24 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_scrapingtask_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingtask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 10, 8, 8, 723320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
