# Generated by Django 5.2.3 on 2025-06-25 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_scrapingtask_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='description',
            new_name='inner_title',
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='author_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='main_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='published_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 25, 9, 15, 29, 711375, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='max_contents',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
