# Generated by Django 5.2.3 on 2025-06-25 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_description_content_inner_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='published_time_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 25, 10, 21, 25, 651796, tzinfo=datetime.timezone.utc)),
        ),
    ]
