# Generated by Django 5.2.3 on 2025-07-02 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_content_published_time_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cover_image_path',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='story_images_paths',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 2, 12, 29, 19, 565634, tzinfo=datetime.timezone.utc)),
        ),
    ]
