
name : Sync to Master

on:
  schedule:
    - cron: '*/30 * * * *' # Every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  sync_to_master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository (Master)
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.MASTER_SYNCH_TOKEN }}

      - name: Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add Backend and Frontend Changes
        run: |
          git remote add backend https://github.com/ashik5757/Prothom_Alo_Scrapper.git
          git remote add frontend https://github.com/ashik5757/prothomalo_scrapping.git
          git fetch backend
          git fetch frontend

      - name: Pull backend changes into /backend
        run: |
          git subtree pull --prefix=backend backend main --squash || echo "No changes in backend"

      - name: Pull frontend changes into /frontend
        run: |
          git subtree pull --prefix=frontend frontend main --squash || echo "No changes in frontend"

      - name: Push Changes to Master
        run: |
          git push origin master
